# Generated by Django 5.2.8 on 2026-07-24 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('job_url', models.URLField()),
                ('job_location', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True)),
                ('job_status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('remote', 'Remote')], default='full_time', max_length=20)),
                ('salary_range', models.CharField(blank=True, choices=[('0-10000', '$0 - $10,000'), ('10000-20000', '$10,000 - $20,000'), ('20000-30000', '$20,000 - $30,000'), ('30000-40000', '$30,000 - $40,000'), ('40000-50000', '$40,000 - $50,000'), ('50000-60000', '$50,000 - $60,000'), ('60000-70000', '$60,000 - $70,000'), ('70000-80000', '$70,000 - $80,000'), ('80000-90000', '$80,000 - $90,000'), ('90000-100000', '$90,000 - $100,000'), ('100000-150000', '$100,000 - $150,000'), ('150000+', 'Greater than $150,000')], max_length=20)),
                ('job_source', models.CharField(choices=[('indeed', 'Indeed'), ('linkedin', 'LinkedIn'), ('monster', 'Monster'), ('glassdoor', 'Glassdoor'), ('company_career_page', 'Company Career Page'), ('google', 'Google'), ('ziprecruiter', 'ZipRecruiter'), ('jobstreet', 'Jobstreet'), ('other', 'Other')], default='other', max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('applied_toggle', models.BooleanField(default=False)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
