# Generated by Django 5.2.8 on 2026-07-19 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeetCodeProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_number', models.IntegerField()),
                ('question', models.CharField(max_length=255)),
                ('problem_link', models.URLField()),
                ('solution_link', models.URLField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('programming_language', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('date_solved', models.DateField()),
                ('next_review_date', models.DateField()),
                ('repetition_count', models.IntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('due_for_review', 'Due for Review'), ('mastered', 'Mastered')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leetcode_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
