# Generated by Django 5.2.8 on 2026-07-21 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DSAConcept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('resource_used', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('mastery_level', models.CharField(choices=[('not_started', 'Not Started'), ('learning', 'Learning'), ('comfortable', 'Comfortable'), ('mastered', 'Mastered')], default='not_started', max_length=20)),
                ('date_studied', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsa_concepts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
