# Generated by Django 5.2.8 on 2026-07-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsaconcept',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='dsa_concepts', to='tags.tag'),
        ),
    ]
